### PR TITLE
Support multi-line mode

### LINKED ISSUE #5: Support multi-line mode
Most regex engines will stop comparing once you hit a newline unless you explicitly pass a multi-line flag. We should support this mode, and update the `^`, `$`, `\A`, and `\z` flags to support it.

### PR DESCRIPTION
**Pull request by Schwad**
Fixes: https://github.com/kddnewton/regular_expression/issues/5

By default we should *not* match `.` to `\n`.

This should be turned on by passing the flag `Regexp::MULTILINE`. (@kddnewton walked down a similar path recently with `Regexp::EXTENDED`).

I've added tests to show the change in the flow.

### CODE REVIEW

**Comment by jbourassa** [comment]
We took a different approach in this WIP commit:

https://github.com/kddnewton/regular_expression/commit/f6690bbafdd3f88cdf64d340cc9e1a6d4eea301a#diff-dacda7193d7e1536ff317b4f658c9d4a52b88983d9b5df632b9efde8e2e0c9d4R283-R291

The pro of changing the NFA is that we can implement the flag once, and it'll propagate to the bytecode thus all the implementations (the interpreter and all compilers). We paused work on the above linked branch to rework the AST->NFA translation first so `flags` do not have to be passed around so much.

Let me know what you think!

**Comment by kddnewton** [comment]
I think ideally we should be adding a new bytecode for this. Instead of `TestAny` maybe `TestNonNewLine`? That way we can insert a different bytecode and everything should _just work_ (in theory).

**Comment by Schwad** [comment]
@jbourassa that's really interesting, would that make the API look like `Pattern.new('abc?de', 'm')`? I may have gone a different path trying to support the use of the rubyish flag `Regexp::MULTILINE` (which returns the `/abc?de/m`). Might need to pair to fully understand 😅 

@kddnewton if I understand correctly might this PR be moot due to the above commit? Even if so, I'd like to update this PR with your idea of adding a new bytecode.

**Comment by jbourassa** [comment]
> @jbourassa that's really interesting, would that make the API look like `Pattern.new('abc?de', 'm')`?

Forget about that part, sorry. I updated the code to use _rubyish flags_, following in Kevin's footsteps, but the link I shared was for a specific commit.

**Comment by kddnewton** [comment]
@Schwad not moot at all! They're working on the case-insensitive one, not multiline. I think the way you extended the flags is perfect as it is. I would just change it so that when you're generating bytecode and you hit an `NFA::Transition::Any` transition that you either add a `TestAny` instruction or a `TestNonNewLine` instruction.

**Pull request closed without merging**
